#! /bin/sh

GPG_PRIVATE_KEY_FILE='/app/config/gpg/privkey.asc'

if [ -f "${GPG_PRIVATE_KEY_FILE}" ]
then
	gpg --import "${GPG_PRIVATE_KEY_FILE}"
fi

ARGOCD_BINARY_NAME="$(basename "$0")" exec "$(dirname "$0")/_$(basename "$0")" "$@"
